import './App.css'
const phone='tel:+4917672116029'
const maps='https://www.google.com/maps/search/?api=1&query=King+Barbershop+Bahnhofstra%C3%9Fe+1+69412+Eberbach'
export default function App(){return <>
<a className="skip" href="#main">Zum Inhalt</a>
<header className="wrap header"><a className="brand" href="#" aria-label="King Barbershop Startseite"><img className="brand-logo" src="/king-logo.jpg" alt="" width="445" height="449"/><span>KING<small>BARBERSHOP · EBERBACH</small></span></a><nav aria-label="Hauptnavigation"><a href="#angebote">Angebote</a><a href="#leistungen">Leistungen</a><a href="#kontakt">Kontakt</a></nav><a className="header-call" href={phone}>Anrufen ↗</a></header>
<main id="main"><section className="wrap hero"><div><p className="eyebrow">DEIN BARBERSHOP IN EBERBACH</p><h1>Dein Schnitt.<br/>Dein Stil.<br/><em>Dein King.</em></h1><p className="intro">Frische Haarschnitte für Männer und Frauen.<br/>Mitten in Eberbach. Ganz unkompliziert.</p><a className="button" href={phone}>Jetzt anrufen <span aria-hidden="true">↗</span></a><a className="discover" href="#angebote">Unsere Angebote entdecken ↓</a></div><figure className="hero-image"><img src="/barber.jpg" alt="Detailaufnahme eines Haarschnitts mit Kamm und Haarschneidemaschine" width="1400" height="1800" fetchPriority="high"/><figcaption>GUTES HANDWERK. GUTER STIL.</figcaption></figure></section>
<div className="info-strip"><div className="wrap"><span>Bahnhofstraße 1 · Eberbach</span><span>Mo–Sa · 09:00–19:00 Uhr</span><a href={phone}>0176 7211 6029 ↗</a></div></div>
<section id="angebote" className="wrap section"><div className="section-heading"><div><p className="eyebrow">GUT AUSSEHEN. WENIGER ZAHLEN.</p><h2>Dein Besuch lohnt sich.</h2></div><p>Zwei Angebote. Ein guter Grund<br/>vorbeizukommen.</p></div><div className="offer-grid"><article className="offer"><div className="offer-top"><span>FÜR MÄNNER</span><span>01 / TREUEBONUS</span></div><div className="offer-number">50<span>%</span></div><h3>Jeder 7. Haarschnitt zum halben Preis.</h3><p>Wiederkommen lohnt sich: Bei jedem siebten Haarschnitt zahlst du nur die Hälfte des regulären Preises.</p><div className="stamps" aria-label="Sechs Besuche, beim siebten halber Preis">{[1,2,3,4,5,6,7].map(n=><span className={n===7?'seventh':''} key={n}>{n}</span>)}<strong>½ Preis</strong></div></article><article className="offer gold"><div className="offer-top"><span>FÜR FRAUEN</span><span>02 / EINFÜHRUNGSANGEBOT</span></div><div className="offer-number">25<span>%</span><small> Rabatt</small></div><h3>Jetzt auch für Damen!</h3><p>25 % Einführungsrabatt auf deinen ersten Haarschnitt. Dein Stil, unsere Leidenschaft.</p><div className="offer-note">Du zahlst nur 75 % des regulären Preises.</div></article></div></section>
<section id="leistungen" className="wrap section services"><div><p className="eyebrow">WAS WIR FÜR DICH TUN</p><h2>Ein guter Schnitt.<br/>Ein gutes Gefühl.</h2><p className="muted">Sag uns, was du dir wünschst.<br/>Wir kümmern uns um deinen Look.</p></div><div className="service-list">{[['Herrenhaarschnitt','Klassisch oder modern – passend zu dir.'],['Damenhaarschnitt','Haarschnitte, Styling und Färben – passend zu deinem Stil.'],['Bart & Konturen','Die Details machen den Unterschied.']].map(([title,description],i)=><div key={title}><span>0{i+1}</span><h3>{title}</h3><p>{description}</p></div>)}<p className="price-note">Preise und Beratung direkt im Salon oder telefonisch.</p></div></section>
<section id="kontakt" className="contact"><div className="wrap section"><p className="eyebrow">WIR FREUEN UNS AUF DICH</p><div className="contact-heading"><h2>Zeit für deinen<br/><em>nächsten Schnitt.</em></h2><a className="button" href={phone}>0176 7211 6029 <span aria-hidden="true">↗</span></a></div><div className="contact-grid"><div><h3>Hier findest du uns</h3><address>King Barbershop<br/>Bahnhofstraße 1<br/>69412 Eberbach</address><a className="underlined" href={maps} target="_blank" rel="noreferrer">Route planen ↗</a></div><div><h3>Unsere Öffnungszeiten</h3><dl><div><dt>Montag – Samstag</dt><dd>09:00 – 19:00</dd></div><div><dt>Sonntag</dt><dd>Geschlossen</dd></div></dl></div><div><h3>Fragen oder Terminwunsch?</h3><p>Ruf uns einfach an. Wir helfen dir gerne weiter.</p><a className="underlined" href={phone}>Jetzt Kontakt aufnehmen ↗</a></div></div></div></section></main><footer className="wrap"><a href="#" className="footer-brand" aria-label="King Barbershop Startseite"><img src="/king-logo.jpg" alt="King Barbershop – goldener Löwe mit Krone" width="445" height="449"/></a><span>Bahnhofstraße 1 · 69412 Eberbach</span><span className="credit">Motivfoto: <a href="https://unsplash.com/photos/a-close-up-of-a-person-cutting-another-persons-hair-MRCdF3qUbp0" target="_blank" rel="noreferrer">Salah Regouane / Unsplash</a></span></footer></>}
